book:
  title: 现代 Java 编程指南
  author: Leon Ding
  description: 一本基于 JDK21 版本讲解 Java21 新特性编程实践书籍，采用 WSL + VSCode 作为基础开发环境。
  language: zh-cn # 语言设置
  theme: default # 主题设置
 

highlight:
  - C
  - Java
  - Rust
  - JavaScript
  - SQL


directory:
  theme: theme # 主题目录
  source: book # markdown 源文件目录
  output: docs # 编译渲染输出目录


nav:
  path: root.yaml # 目录映射文件


theme:
  name: default
  custom_css: assets/custom.css  # 自定义CSS文件
  custom_js: assets/custom.js    # 自定义JS文件
  logo: assets/logo.png          # 网站Logo

markdown:
  extensions:
    - markdown.extensions.extra
    - markdown.extensions.codehilite
    - markdown.extensions.toc
  output:
    format: html # 输出格式

deployment:
  provider: github-pages # 部署方式
  repository: git@github.com:auula/posey.git # 仓库地址
  branch: gh-pages # 分支

